const $ = s => document.querySelector(s);
const uid = () => Math.random().toString(36).slice(2, 10);
const now = () => new Date().toISOString().slice(0,10);
const toast = msg => { const t=$('#toast'); t.textContent=msg; t.className='show'; setTimeout(()=>t.className='',2200); };
const DATA_VERSION = 'v5_30fan_50teacher_50student_30tests';
const store = {
  get(){
    const savedVersion = localStorage.getItem('mp_version');
    if(savedVersion !== DATA_VERSION){ localStorage.removeItem('mp_data'); localStorage.removeItem('mp_user'); localStorage.setItem('mp_version', DATA_VERSION); }
    return JSON.parse(localStorage.getItem('mp_data') || 'null') || seed();
  },
  set(d){ localStorage.setItem('mp_data', JSON.stringify(d)); },
  user(){ return JSON.parse(localStorage.getItem('mp_user') || 'null'); },
  setUser(u){ localStorage.setItem('mp_user', JSON.stringify(u)); },
  logout(){ localStorage.removeItem('mp_user'); }
};
const teacherNames = ['Akmal Normurodov','Dilshod Rahimov','Zarina Qodirova','Shaxzod Sobirov','Muhammadali To‘xtayev','Islom Ismoilov','Aziza Karimova','Jasur To‘rayev','Nodira Amonova','Bobur Yo‘ldoshev','Sevara Tursunova','Bekzod Aliyev','Madina Rasulova','Sardor Qahhorov','Malika Karimova','Azizbek Akmalov','Diyor Valiyev','Shohruh Rustamov','Gulnoza Ergasheva','Komil Sattorov','Umida Xolmatova','Farrux Nabiyev','Sarvinoz Abdukarimova','Oybek Oripov','Zilola Usmonova','Alisher Erkinov','Nargiza Jo‘rayeva','Temur Mahmudov','Mohira Shamsiyeva','Sherzod Abdullayev','Jamila Murodova','Ibrohim Saidov','Feruza Hamidova','Otabek Yunusov','Durdona Sobirova','Ulug‘bek Xudoyberdiyev','Lola Safarova','Bahodir Juraev','Mavluda Xakimova','Abror Tohirov','Shahnoza Olimova','Davron Bekmurodov','Nilufar Mirzayeva','Rustam Mamatqulov','Gavhar Raximova','Sanjar Haydarov','Munisa Abduraimova','Sirojiddin Meliyev','Dilorom Akbarova','Javohir Abdullayev'];
const studentNames = ['Akmalov Aziz','Valiyev Diyor','Karimova Malika','Yo‘ldoshev Bobur','Tursunova Sevara','Aliyev Bekzod','Rasulova Madina','Qahhorov Sardor','Sobirov Shaxzod','To‘xtayev Muhammadali','Amonova Nodira','Ismoilov Ilhom','Ergasheva Gulnoza','Sattorov Komil','Xolmatova Umida','Nabiyev Farrux','Abdukarimova Sarvinoz','Oripov Oybek','Usmonova Zilola','Erkinov Alisher','Jo‘rayeva Nargiza','Mahmudov Temur','Shamsiyeva Mohira','Abdullayev Sherzod','Murodova Jamila','Saidov Ibrohim','Hamidova Feruza','Yunusov Otabek','Sobirova Durdona','Xudoyberdiyev Ulug‘bek','Safarova Lola','Juraev Bahodir','Xakimova Mavluda','Tohirov Abror','Olimova Shahnoza','Bekmurodov Davron','Mirzayeva Nilufar','Mamatqulov Rustam','Raximova Gavhar','Haydarov Sanjar','Abduraimova Munisa','Meliyev Sirojiddin','Akbarova Dilorom','Abdullayev Javohir','Qodirov Elyor','Nazarova Maftuna','Rahmonov Asadbek','Sharipova Dilafruz','Norboyev Sarvar','Anvarova Laylo'];
const courseNames = ['Dasturlash asoslari','Elektronika asoslari','Kompyuter tarmoqlari','Ma’lumotlar bazasi','Avtomatika va boshqaruv','Raqamli sxemalar','Mikroprotsessor tizimlari','Robototexnika asoslari','Sun’iy intellekt asoslari','Veb dasturlash','Mobil ilovalar yaratish','Axborot xavfsizligi','Operatsion tizimlar','Bulutli texnologiyalar','IoT tizimlari','Mexatronika','Elektr mashinalari','Telekommunikatsiya tizimlari','Signallarni qayta ishlash','Kompyuter grafikasi','CAD/CAM texnologiyalari','Matlab va Simulink','Energetika tizimlari','Kiberxavfsizlik amaliyoti','Sanoat tarmoqlari','Sensorlar va aktuatorlar','Ma’lumotlar tahlili','Algoritmlar va tuzilmalar','Loyiha boshqaruvi','Muhandislik pedagogikasi'];
function seed(){
 const users=[{id:'u_admin',name:'Administrator',username:'admin',password:'admin123',role:'admin',group:'Boshqaruv'}];
 teacherNames.forEach((name,i)=>users.push({id:`t${i+1}`,name:`O‘qituvchi ${name}`,username:`teacher${i+1}`,password:'teacher123',role:'teacher',group:'Muhandislik'}));
 studentNames.forEach((name,i)=>users.push({id:`s${i+1}`,name:`Talaba ${name}`,username:`student${i+1}`,password:'student123',role:'student',group:`NG-${21+(i%5)}`}));
 const courses=courseNames.map((name,i)=>({id:`c${i+1}`,name,teacher:`O‘qituvchi ${teacherNames[i%teacherNames.length]}`,credits:3+(i%3),desc:`${name} bo‘yicha nazariy materiallar, amaliy topshiriqlar va laboratoriya ishlari.`}));
 const assignments=courses.map((c,i)=>({id:`a${i+1}`,course:c.id,title:['LAN tarmoq yaratish','Elektr zanjirini hisoblash','Algoritm yaratish','SQL so‘rovlarini yozish','Avtomatik boshqaruv modeli'][i%5]+` #${i+1}`,deadline:`2026-06-${String(10+(i%18)).padStart(2,'0')}`,points:100,desc:`${c.name} faniga oid individual amaliy topshiriq. Natija, jadval, tahlil va xulosa kiritiladi.`}));
 const materials=courses.map((c,i)=>({id:`m${i+1}`,course:c.id,title:`${c.name} bo‘yicha ma’ruza materiallari`,type:i%3===0?'PDF':i%3===1?'Video':'Ma’ruza',url:'#'}));
 const labs=courses.map((c,i)=>({id:`l${i+1}`,course:c.id,title:`${c.name} laboratoriya ishi`,goal:`${c.name} bo‘yicha amaliy ko‘nikmani shakllantirish`,steps:'1. Vazifani tahlil qiling. 2. Model yoki sxema yarating. 3. Natijalarni jadvalga yozing. 4. Xulosa tayyorlang.',tool:['Cisco Packet Tracer','Tinkercad','MATLAB Simulink','Proteus','Browser IDE'][i%5]}));
 const tests=courses.slice(0,30).map((c,i)=>({id:`test${i+1}`,course:c.id,title:`${c.name} testi`,questions:[
  {q:`${c.name} fanida amaliy mashg‘ulotning asosiy maqsadi nima?`,a:['Kompetensiya shakllantirish','Faqat matn o‘qish','Kompyuterni o‘chirish'],c:0},
  {q:'Hisobotda nimalar bo‘lishi kerak?',a:['Natija, tahlil va xulosa','Faqat ism','Bo‘sh sahifa'],c:0},
  {q:'Amaliy topshiriqni baholashda eng muhim mezon qaysi?',a:['To‘g‘ri bajarish va tahlil','Faqat rangli dizayn','Fayl nomi uzunligi'],c:0},
  {q:'Virtual laboratoriya qanday imkoniyat beradi?',a:['Tajribani xavfsiz modellashtirish','Kompyuterni ta’mirlash','Parolni almashtirish'],c:0},
  {q:'Monitoring moduli nima uchun kerak?',a:['Talaba faolligi va natijalarni kuzatish','Faqat rasm chizish','Internet tezligini oshirish'],c:0}
]}));
 const submissions=[];
 for(let i=0;i<20;i++){ submissions.push({id:`sub${i+1}`,assignment:`a${(i%30)+1}`,student:`s${(i%50)+1}`,text:'Topshiriq bajarildi, natijalar tahlil qilindi va xulosa yozildi.',file:`hisobot_${i+1}.pdf`,date:now(),grade:70+(i%26),comment:'Yaxshi bajarilgan'}); }
 const activity=[{date:now(),user:'u_admin',action:'Tizimga kirdi'}];
 for(let i=0;i<30;i++) activity.push({date:now(),user:`s${(i%50)+1}`,action:i%3===0?'Hisobot topshirdi':i%3===1?'Test ishladi':'Platformaga kirdi'});
 const d={users,courses,materials,assignments,labs,tests,submissions,activity}; store.set(d); return d;
}
let db=store.get(), current=store.user(), page='dashboard', chart;
const roleName={admin:'Administrator',teacher:'O‘qituvchi',student:'Talaba'};
const menus={admin:['dashboard','users','teachers','students','courses','materials','assignments','labs','tests','reports','grades','monitoring'],teacher:['dashboard','courses','materials','assignments','labs','tests','reports','grades','monitoring'],student:['dashboard','courses','materials','assignments','labs','tests','reports','grades']};
const titles={dashboard:'Bosh sahifa',users:'Foydalanuvchilar',teachers:'O‘qituvchilar',students:'Talabalar',courses:'Fanlar',materials:'Nazariy materiallar',assignments:'Amaliy topshiriqlar',labs:'Laboratoriyalar',tests:'Test nazorati',reports:'Hisobotlar',grades:'Baholash',monitoring:'Monitoring'};
function save(){store.set(db)}
function log(action){ if(current){ db.activity.unshift({date:now(),user:current.id,action}); save(); }}
function init(){ if(current) showApp(); else showLogin(); }
function showLogin(){ $('#loginPage').classList.remove('hidden'); $('#appPage').classList.add('hidden'); }
function showApp(){ $('#loginPage').classList.add('hidden'); $('#appPage').classList.remove('hidden'); renderNav(); render(); }
$('#loginForm').onsubmit=e=>{e.preventDefault(); const u=$('#loginUsername').value.trim(), p=$('#loginPassword').value; const found=db.users.find(x=>x.username===u&&x.password===p); if(!found) return toast('Login yoki parol xato'); current=found; store.setUser(found); log('Tizimga kirdi'); showApp();};
function doLogout(){ store.logout(); current=null; toast('Tizimdan chiqildi'); setTimeout(()=>location.reload(),350); }
$('#logoutBtn').onclick=doLogout;
function renderNav(){ $('#navMenu').innerHTML=menus[current.role].map(m=>`<button class="nav-btn ${page===m?'active':''}" onclick="go('${m}')">${titles[m]} ${badgeFor(m)}</button>`).join(''); $('#userPill').innerHTML=`${current.name}<br><span class="muted">${roleName[current.role]}</span>`;}
function badgeFor(m){ const map={users:db.users.length,teachers:teachersList().length,students:studentsList().length,courses:db.courses.length,assignments:db.assignments.length,labs:db.labs.length,tests:db.tests.length}; return map[m]?`<span class="badge" style="float:right">${map[m]}</span>`:''; }
function go(p){page=p; renderNav(); render();}
function render(){ $('#pageTitle').textContent=titles[page]; $('#pageSubtitle').textContent='Muhandislik fanlari amaliy mashg‘ulotlari uchun raqamli boshqaruv muhiti'; const map={dashboard,users,teachers,students,courses,materials,assignments,labs,tests,reports,grades,monitoring}; $('#content').innerHTML=map[page](); setTimeout(afterRender,30);}
function teachersList(){return db.users.filter(u=>u.role==='teacher')} function studentsList(){return db.users.filter(u=>u.role==='student')}
function countSub(){return db.submissions.length} function avgGrade(){let a=db.submissions.filter(s=>s.grade!=null);return a.length?Math.round(a.reduce((x,y)=>x+y.grade,0)/a.length):0}
function dashboard(){return `<div class="grid grid-5"><div class="card stat"><h3>Foydalanuvchilar</h3><b>${db.users.length}</b><small>Jami foydalanuvchi</small></div><div class="card stat"><h3>O‘qituvchilar</h3><b>${teachersList().length}</b><small>Faol o‘qituvchi</small></div><div class="card stat"><h3>Talabalar</h3><b>${studentsList().length}</b><small>Faol talaba</small></div><div class="card stat"><h3>Fanlar</h3><b>${db.courses.length}</b><small>Jami fanlar</small></div><div class="card stat"><h3>Topshiriqlar</h3><b>${db.assignments.length}</b><small>Jami topshiriq</small></div></div><div class="grid grid-2" style="margin-top:18px"><div class="card chart-box"><h2>Faoliyat statistikasi</h2><canvas id="mainChart"></canvas></div><div class="card"><h2>So‘nggi faoliyatlar</h2><div class="dash-list">${db.activity.slice(0,8).map(a=>`<div class="dash-row"><span><b>${studentName(a.user)}</b><br><span class="muted">${a.action}</span></span><span class="muted">${a.date}</span></div>`).join('')}</div></div></div><div class="grid grid-3" style="margin-top:18px"><div class="card"><h2>Top fanlar</h2>${table(['#','Fan','O‘qituvchi'],db.courses.slice(0,5).map((c,i)=>[i+1,c.name,c.teacher]))}</div><div class="card"><h2>Top talabalar</h2>${table(['#','Talaba','Ball'],studentsList().slice(0,5).map((s,i)=>[i+1,s.name,95-i*2]))}</div><div class="card"><h2>Top o‘qituvchilar</h2>${table(['#','O‘qituvchi','Topshiriq'],teachersList().slice(0,5).map((t,i)=>[i+1,t.name,30-i]))}</div></div>`}
function users(){ if(current.role!=='admin') return deny(); return `<div class="card"><div class="toolbar"><h2>Foydalanuvchilar (${db.users.length})</h2><button onclick="openUserForm()">Yangi foydalanuvchi</button></div><div id="userForm"></div>${table(['Ism','Login','Rol','Guruh','Amal'],db.users.map(u=>[u.name,u.username,roleName[u.role],u.group,u.role==='admin'?'-':`<button class="small danger-btn" onclick="delUser('${u.id}')">O‘chirish</button>`]))}</div>`}
function teachers(){ if(current.role!=='admin') return deny(); return `<div class="card"><div class="toolbar"><h2>O‘qituvchilar (${teachersList().length})</h2><button onclick="openUserForm('teacher')">O‘qituvchi qo‘shish</button></div><div id="userForm"></div>${table(['#','Ism','Login','Parol','Yo‘nalish'],teachersList().map((u,i)=>[i+1,u.name,u.username,'teacher123',u.group]))}</div>`}
function students(){ if(current.role!=='admin') return deny(); return `<div class="card"><div class="toolbar"><h2>Talabalar (${studentsList().length})</h2><button onclick="openUserForm('student')">Talaba qo‘shish</button></div><div id="userForm"></div>${table(['#','Ism','Login','Parol','Guruh'],studentsList().map((u,i)=>[i+1,u.name,u.username,'student123',u.group]))}</div>`}
function courses(){return `<div class="card"><div class="toolbar"><h2>Fanlar katalogi (${db.courses.length})</h2>${current.role!=='student'?'<button onclick="openCourseForm()">Fan qo‘shish</button>':''}</div><div id="courseForm"></div><div class="grid grid-3">${db.courses.map(c=>`<div class="card course-card"><h3>${c.name}</h3><p>${c.desc}</p><span class="badge">${c.credits} kredit</span><p class="muted">${c.teacher}</p>${current.role!=='student'?`<button class="small danger-btn" onclick="delCourse('${c.id}')">O‘chirish</button>`:''}</div>`).join('')}</div></div>`}
function materials(){return crudPage('Nazariy materiallar','Material qo‘shish','materialForm', current.role!=='student', ['Fan','Nomi','Turi','Havola','Amal'], db.materials.map(m=>[courseName(m.course),m.title,m.type,m.url,current.role!=='student'?`<button class="small danger-btn" onclick="delItem('materials','${m.id}')">O‘chirish</button>`:'-']))}
function assignments(){return `<div class="card"><div class="toolbar"><h2>Amaliy topshiriqlar (${db.assignments.length})</h2>${current.role!=='student'?'<button onclick="openAssignmentForm()">Topshiriq qo‘shish</button>':''}</div><div id="assignmentForm"></div>${table(['Fan','Topshiriq','Muddat','Ball','Holat','Amal'],db.assignments.map(a=>{let sub=db.submissions.find(s=>s.assignment===a.id&&s.student===current.id);return [courseName(a.course),`<b>${a.title}</b><br><span class="muted">${a.desc}</span>`,a.deadline,a.points,sub?'<span class="badge ok">Topshirilgan</span>':'<span class="badge warn">Kutilmoqda</span>',current.role==='student'?`<button class="small" onclick="openSubmit('${a.id}')">Hisobot topshirish</button>`:`<button class="small danger-btn" onclick="delItem('assignments','${a.id}')">O‘chirish</button>`]}))}<div id="submitForm"></div></div>`}
function labs(){return `<div class="card"><div class="toolbar"><h2>Laboratoriya ishlari (${db.labs.length})</h2>${current.role!=='student'?'<button onclick="openLabForm()">Laboratoriya qo‘shish</button>':''}</div><div id="labForm"></div><div class="grid grid-3">${db.labs.map(l=>`<div class="card lab-card"><h3>${l.title}</h3><p><b>Maqsad:</b> ${l.goal}</p><p><b>Vosita:</b> ${l.tool}</p><p class="muted">${l.steps}</p>${current.role!=='student'?`<button class="small danger-btn" onclick="delItem('labs','${l.id}')">O‘chirish</button>`:''}</div>`).join('')}</div></div>`}
function tests(){return `<div class="card"><h2>Test nazorati (${db.tests.length} ta test)</h2>${current.role==='student'?db.tests.map(t=>`<div class="question"><h3>${t.title}</h3>${t.questions.map((q,i)=>`<p><b>${i+1}. ${q.q}</b></p>${q.a.map((a,j)=>`<label class="answer"><input type="radio" name="${t.id}_${i}" value="${j}">${a}</label>`).join('')}`).join('')}<button onclick="finishTest('${t.id}')">Testni yakunlash</button></div>`).join(''):'<p>Test savollari banki mavjud. Talaba panelida test ishlash mumkin.</p>'+table(['Fan','Test','Savollar'],db.tests.map(t=>[courseName(t.course),t.title,t.questions.length]))}</div>`}
function reports(){let rows=db.submissions.filter(s=>current.role==='student'?s.student===current.id:true).map(s=>[studentName(s.student),assignName(s.assignment),s.text,s.file,s.date,s.grade??'Baholanmagan']); return `<div class="card"><h2>Hisobotlar (${rows.length})</h2>${table(['Talaba','Topshiriq','Matn','Fayl','Sana','Ball'],rows)}</div>`}
function grades(){let rows=db.submissions.filter(s=>current.role==='student'?s.student===current.id:true).map(s=>[studentName(s.student),assignName(s.assignment),s.grade??'',s.comment??'',current.role!=='student'?`<button class="small" onclick="openGrade('${s.id}')">Baholash</button>`:'-']); return `<div class="card"><h2>Baholash</h2>${table(['Talaba','Topshiriq','Ball','Izoh','Amal'],rows)}<div id="gradeForm"></div></div>`}
function monitoring(){ if(current.role==='student') return deny(); return `<div class="grid grid-2"><div class="card chart-box"><h2>Monitoring grafigi</h2><canvas id="monitorChart"></canvas></div><div class="card"><h2>Faollik jurnali</h2>${table(['Sana','Foydalanuvchi','Harakat'],db.activity.slice(0,18).map(a=>[a.date,studentName(a.user),a.action]))}</div></div>`}
function deny(){return '<div class="card"><h2>Ruxsat yo‘q</h2><p>Bu bo‘lim faqat tegishli rol uchun ochiladi.</p></div>'}
function table(h,rows){return `<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function courseName(id){return db.courses.find(c=>c.id===id)?.name||'-'} function studentName(id){return db.users.find(u=>u.id===id)?.name||'-'} function assignName(id){return db.assignments.find(a=>a.id===id)?.title||'-'}
function courseSelect(){return db.courses.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function openUserForm(role='student'){ $('#userForm').innerHTML=`<form class="form-grid" onsubmit="addUser(event)"><input name="name" placeholder="Ism" required><input name="username" placeholder="Login" required><input name="password" placeholder="Parol" value="${role==='teacher'?'teacher123':'student123'}" required><select name="role"><option value="student" ${role==='student'?'selected':''}>Talaba</option><option value="teacher" ${role==='teacher'?'selected':''}>O‘qituvchi</option><option value="admin">Admin</option></select><input name="group" placeholder="Guruh / yo‘nalish"><button>Saqlash</button></form>`}
function addUser(e){e.preventDefault(); let f=Object.fromEntries(new FormData(e.target)); db.users.push({id:uid(),...f}); save(); toast('Foydalanuvchi qo‘shildi'); render();}
function delUser(id){db.users=db.users.filter(u=>u.id!==id); save(); render();}
function openCourseForm(){ $('#courseForm').innerHTML=`<form class="form-grid" onsubmit="addCourse(event)"><input name="name" placeholder="Fan nomi" required><input name="credits" type="number" placeholder="Kredit"><input name="teacher" placeholder="O‘qituvchi"><textarea class="full" name="desc" placeholder="Fan tavsifi"></textarea><button>Saqlash</button></form>`}
function addCourse(e){e.preventDefault(); db.courses.push({id:uid(),...Object.fromEntries(new FormData(e.target))}); save(); toast('Fan qo‘shildi'); render();}
function delCourse(id){db.courses=db.courses.filter(c=>c.id!==id); save(); render();}
function openAssignmentForm(){ $('#assignmentForm').innerHTML=`<form class="form-grid" onsubmit="addAssignment(event)"><select name="course">${courseSelect()}</select><input name="title" placeholder="Topshiriq nomi" required><input name="deadline" type="date" required><input name="points" type="number" value="100"><textarea class="full" name="desc" placeholder="Topshiriq mazmuni"></textarea><button>Saqlash</button></form>`}
function addAssignment(e){e.preventDefault(); db.assignments.push({id:uid(),...Object.fromEntries(new FormData(e.target))}); save(); toast('Topshiriq qo‘shildi'); render();}
function openLabForm(){ $('#labForm').innerHTML=`<form class="form-grid" onsubmit="addLab(event)"><select name="course">${courseSelect()}</select><input name="title" placeholder="Laboratoriya nomi" required><input name="goal" placeholder="Maqsad"><input name="tool" placeholder="Dasturiy vosita"><textarea class="full" name="steps" placeholder="Bajarish tartibi"></textarea><button>Saqlash</button></form>`}
function addLab(e){e.preventDefault(); db.labs.push({id:uid(),...Object.fromEntries(new FormData(e.target))}); save(); toast('Laboratoriya qo‘shildi'); render();}
function openSubmit(id){ $('#submitForm').innerHTML=`<form class="card form-grid" onsubmit="submitReport(event,'${id}')"><textarea class="full" name="text" placeholder="Bajarilgan ishlar, natijalar, tahlil va xulosa" required></textarea><input name="file" placeholder="Fayl nomi: hisobot.pdf"><button>Hisobotni yuborish</button></form>`; location.hash='submitForm';}
function submitReport(e,id){e.preventDefault(); let f=Object.fromEntries(new FormData(e.target)); let old=db.submissions.find(s=>s.assignment===id&&s.student===current.id); if(old) Object.assign(old,f,{date:now(),grade:null,comment:''}); else db.submissions.push({id:uid(),assignment:id,student:current.id,...f,date:now(),grade:null,comment:''}); log('Hisobot topshirdi'); toast('Hisobot yuborildi'); render();}
function openGrade(id){let s=db.submissions.find(x=>x.id===id); $('#gradeForm').innerHTML=`<form class="card form-grid" onsubmit="saveGrade(event,'${id}')"><input name="grade" type="number" min="0" max="100" value="${s.grade??''}" placeholder="Ball"><textarea class="full" name="comment" placeholder="Izoh">${s.comment??''}</textarea><button>Bahoni saqlash</button></form>`}
function saveGrade(e,id){e.preventDefault(); let f=Object.fromEntries(new FormData(e.target)); let s=db.submissions.find(x=>x.id===id); s.grade=Number(f.grade); s.comment=f.comment; log('Hisobot baholandi'); save(); toast('Baho saqlandi'); render();}
function delItem(k,id){db[k]=db[k].filter(x=>x.id!==id); save(); render();}
function finishTest(id){let t=db.tests.find(x=>x.id===id), score=0; t.questions.forEach((q,i)=>{let v=document.querySelector(`input[name="${id}_${i}"]:checked`); if(v&&Number(v.value)===q.c) score++;}); let percent=Math.round(score/t.questions.length*100); db.submissions.push({id:uid(),assignment:id,student:current.id,text:'Test natijasi',file:'-',date:now(),grade:percent,comment:`${score}/${t.questions.length} to‘g‘ri`}); log('Test ishladi'); save(); toast(`Test natijasi: ${percent} ball`); render();}
function afterRender(){ if(page==='dashboard' && $('#mainChart')) makeChart('mainChart',['Yan','Fev','Mar','Apr','May','Iyun'],[45,60,78,69,91,84]); if(page==='monitoring' && $('#monitorChart')) makeChart('monitorChart',['O‘z vaqtida','Test','Hisobot','Faollik','Baholash'],[86,82,85,83,88]); }
function makeChart(id,labels,data){ if(chart) chart.destroy(); chart=new Chart(document.getElementById(id),{type:'line',data:{labels,datasets:[{label:'Ko‘rsatkich',data,fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,max:100}}}});}
function crudPage(title,btn,formId,can,h,rows){return `<div class="card"><div class="toolbar"><h2>${title}</h2>${can?`<button onclick="openMaterialForm()">${btn}</button>`:''}</div><div id="${formId}"></div>${table(h,rows)}</div>`}
function openMaterialForm(){ $('#materialForm').innerHTML=`<form class="form-grid" onsubmit="addMaterial(event)"><select name="course">${courseSelect()}</select><input name="title" placeholder="Material nomi" required><input name="type" placeholder="PDF / Video / Ma’ruza"><input name="url" placeholder="Havola yoki fayl nomi"><button>Saqlash</button></form>`}
function addMaterial(e){e.preventDefault(); db.materials.push({id:uid(),...Object.fromEntries(new FormData(e.target))}); save(); toast('Material qo‘shildi'); render();}
function searchPage(q){ q=(q||'').toLowerCase(); document.querySelectorAll('tbody tr,.course-card,.lab-card').forEach(el=>{el.style.display=el.textContent.toLowerCase().includes(q)?'':'none'}); }
init();
